### ISSUE TITLE
How do I specify the background color for CodeEditor?

### ISSUE THREAD

**Issue by jasudev** [ZeeZide/CodeEditor#1]
hi~
First of all, thank you for sharing a great solution.
How do I specify the background color for CodeEditor?

**Comment by helje5** [comment]
This is controlled by the Highlightr theme, eg use a dark theme for dark mode.

**Comment by Rminsh** [comment]
#16 

> hi~ First of all, thank you for sharing a great solution. How do I specify the background color for CodeEditor?
