### ISSUE TITLE
How to use a customized font in IOS? 

### ISSUE THREAD

**Issue by InkosiZhong** [ZeeZide/CodeEditor#19]
I switched from SwiftUI's `TextEditor` to this `CodeEditor`. it really amazed me.
However, I found I cannot specify the font and font size as I did in the `TextEditor`. The code is as follow,
```Swift
CodeEditor(source: $formulaInput, language: .python, theme: .default,
                       autoPairs: ["(" : ")", "{" : "}", "[" : "]"])
                .font(.custom("SF Mono Bold", size: fontSize))
```
Can you teach me how to use a customized font?
Thank you so much

**Comment by helje5** [comment]
The `fontSize` is just a regular binding of CodeEditor, e.g.
```swift
CodeEditor(
  source: $formulaInput, language: .python, theme: .default,
  fontSize: .constant(20),
  autoPairs: ["(" : ")", "{" : "}", "[" : "]"]
)
```
should do. Also check: https://github.com/ZeeZide/CodeEditor/blob/180bde07b44dea839b32873bd8586ba146fa9106/Sources/CodeEditor/CodeEditor.swift#L93

The font itself is part of the Highlightr theme: https://github.com/ZeeZide/CodeEditor/blob/180bde07b44dea839b32873bd8586ba146fa9106/Sources/CodeEditor/UXCodeTextView.swift#L57
I don't remember how you would change that as it seems to be accessed by name. Might require a custom Highlightr.
