### ISSUE TITLE
Add a Binding to report the currently selected range

### ISSUE THREAD

**Issue by SwiftDevJournal** [ZeeZide/CodeEditor#2]
I want to insert some text in the code editor. Markdown example: Select some text, press Cmd-B for Bold, and have two asterisks inserted before and after the selection. But to do this, I need to get the code editor's selection range. How do I get the selection range?

**Comment by helje5** [comment]
The `CodeEditor` View doesn't currently support this feature, but it could. The backing text object would just need to track the selection of the backing host view and report that in a binding. It would be a neat addition!
