### ISSUE TITLE
Can this support markdown (MD) files ?

### ISSUE THREAD

**Issue by pkasson** [ZeeZide/CodeEditor#25]

**Comment by helje5** [comment]
https://github.com/ZeeZide/CodeEditor/blob/180bde07b44dea839b32873bd8586ba146fa9106/Sources/CodeEditor/Language.swift#L43

**Comment by pkasson** [comment]
My bad ... was looking at the theme instead of language.

Choosing MD, it does colorize things, but not formatting I think (attached code and screen shots below)

`
      CodeEditor(source  : $activeItemModel.item.body,
                 language : .markdown,
                 theme    : model.selectedTheme,
                 flags    : [ .selectable, .editable, .smartIndent ],
                 autoPairs: [ "{": "}", "<": ">", "'": "'" ]
`

<img width="1680" alt="Screenshot 2023-05-01 at 11 16 51 AM" src="https://user-images.githubusercontent.com/3072247/235475485-42dbc808-9b2f-44f4-a481-dacf2734b60d.png">

**Comment by helje5** [comment]
Correct, this is a CodeEditor, not a WYSIWYG editor.

**Comment by pkasson** [comment]
understood this is not an editor - but didn't know, if I could extend something to allow it to render MD

**Comment by helje5** [comment]
Sure, you can!

**Comment by pkasson** [comment]
Any insights on how to proceed ?  would certainly push it back as a PR

**Comment by helje5** [comment]
As mentioned such a PR would be out of scope, this isn't supposed to be a WYSIWYG editor for any format. If you want to add this in a fork, that is perfectly fine and you are welcome. You'd have to do the necessary processing and apply the styles to the textstorage. TBH that feels quite different to this project though (which is about syntax highlighting), I would recommend to just implement it for MD from the start then. A sensible markdown editor is no small task though.

**Comment by pkasson** [comment]
Understood - the use case I have is more of a renderer than editor.

**Comment by helje5** [comment]
A Markdown renderer is directly built into the latest SwiftUI versions.

**Comment by pkasson** [comment]
I did try that (Text component) but it is not perfect .. but better than nothing for now, I guess.
