### ISSUE TITLE
Typing is slow and the theme is updated when typing is completed

### ISSUE THREAD

**Issue by pkasson** [ZeeZide/CodeEditor#27]
When typing into the editor window, it is slow as the theme tries to catchup.

**Comment by helje5** [comment]
Yes, this project is not suitable for bigger source files. You might want to have a look at [Runestone](https://github.com/simonbs/runestone) for such.

**Comment by pkasson** [comment]
That appears to be for iOS ... looking for MacOS support.

**Comment by helje5** [comment]
It does have macOS support.
