### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by iliasaz** [ZeeZide/CodeEditor#4]
Hello,
Thanks for this great library!

A beginner's question: what's the easiest way to add keyboard shortcuts? I'd like to execute a closure upon receiving a specific keyboard combination, ex. Cmd-R.

Thanks!

**Comment by helje5** [comment]
Hi, Apple has a wealth of information about SwiftUI readily available:

  https://developer.apple.com/videos/

An example from one of my own apps, [HMScriptEditor](https://apps.apple.com/us/app/hmscripteditor/id1483239744):
```swift
      Button(action: run) {
        Label("Run", systemImage: "play.fill")
      }
      .help("Run the HomeMatic script on the base station")
      .keyboardShortcut("r", modifiers: .command)
```

**Comment by iliasaz** [comment]
oh, this is much easier than I thought. Thank you so much!
